import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/compound/navbar";
import Footer from "./components/compound/Footer";

const inter = Inter({ subsets: ["latin"] });
const popins = Poppins({weight:["100","200","400"], subsets:["latin"]  });
export const metadata: Metadata = {
  title: "Hexa Automation",
  description: "Generated by DiArMo dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={popins.className}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
